name: qube_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  velocity_x: ^3.5.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.2
  extended_image: ^6.2.1
  intl: ^0.17.0
  url_launcher: ^6.1.5
  dio: ^4.0.6

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true
  assets:
    - assets/images/.
  fonts:
  - family: SFPro
    fonts: 
      - asset: assets/fonts/sfpro.ttf

